name: VLESS Action
on: [workflow_dispatch]
jobs:
  run-xray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Run Xray
        run: |
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o Xray-linux-64.zip
          ./xray -c config.json &
          sleep 21600
